#server
server:
  port: 8080
  servlet:
    session:
      timeout: 30m

#db
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: Ewmadminpassword2024%
    url: jdbc:mysql://localhost:3306/ewm
    username: ewm
  jpa:
    generate-ddl: false
  flyway:
    baseline-on-migrate: true
  session:
    store-type: jdbc
    jdbc:
      table-name: SPRING_SESSION

#lombok
lombok:
  log:
    slf4j:
      flagUsage: [info | warning | error]

#custom
ewm:
  api:
    version: v1
  #security
  jwt:
    secret: aJFPB4rb1xfvLW13XfBbjNs5gagHnxoUzkGjs6kPaR0enXufK2QQpUh+4vkMBuAYKpsTdPfvQrzsykbt5nAL2Q==
    expiration: 300000
  #CORS
  origin:
    localhost: http://localhost:8081
