server:
    port: 9090
spring:
    datasource:
        driverClassName:
        password: ${DB_PASSWORD}
        url: ${STAT_DB_URL}
        username: ${DB_USER}
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: MySQL8Dialect
                format_sql: true
