server:
    port: 9090
spring:
    datasource:
        driverClassName:
        password: ewm
        url: jdbc:postgresql://localhost:5433/ewm-statistics
        username: ewm
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: MySQL8Dialect
                format_sql: true
