CREATE TABLE IF NOT EXISTS hits (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(255) NOT NULL,
    ip VARCHAR(255) NOT NULL,
    timestamp VARCHAR(255) NOT NULL
);
